# Generated by Django 5.2.3 on 2025-06-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acharya_ai", "0002_add_hr_features"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interview",
            name="resume_template",
        ),
        migrations.AddField(
            model_name="interview",
            name="resume_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
