# Generated by Django 5.2.3 on 2025-06-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photoURL",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
