# Generated by Django 5.2.3 on 2025-06-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_photourl"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("candidate", "Candidate"), ("hr", "HR")],
                default="candidate",
                max_length=10,
            ),
        ),
    ]
